/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model3D;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;
import java.util.ArrayList;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Phat
 */
public class KTDH_Nhom8 extends javax.swing.JFrame {

    ArrayList<Shape3D> list = new ArrayList<>();
    ArrayList<Shape3D> listRedo = new ArrayList<>();

    UndoManager n = new UndoManager();
    static Graphics g;
    public static int step = 5, graphWidth, graphHeight;

//    public int getGraphWidth() {
//        return graphWidth;
//    }
//
//    public void setGraphWidth(int graphWidth) {
//        this.graphWidth = graphWidth;
//    }
//
//    public int getGraphHeight() {
//        return graphHeight;
//    }
//
//    public void setGraphHeight(int graphHeight) {
//        this.graphHeight = graphHeight;
//    }
    /**
     * Creates new form Draw3D
     */
    public KTDH_Nhom8() {
        initComponents();
        this.g = jPanel_Graph.getGraphics();
        this.setLocationRelativeTo(null);

    }

    private void initGraph(Graphics g) {
        System.out.println(g);
        Graphics2D g2d = (Graphics2D) g;
        step = 5;
        graphHeight = jPanel_Graph.getBounds().height;
        graphWidth = jPanel_Graph.getBounds().width;

        //Vẽ lưới pixel
        g2d.setColor(new Color(238, 238, 238));
        for (int i = 0; i < graphWidth; i += step) {
            g.drawLine(graphWidth / 2 - i, graphHeight / 2 - graphHeight / 2, graphWidth / 2 - i, graphHeight / 2 + graphHeight / 2);
            g.drawLine(graphWidth / 2 + i, graphHeight / 2 - graphHeight / 2, graphWidth / 2 + i, graphHeight / 2 + graphHeight / 2);
            g.drawLine(graphWidth / 2 - graphWidth / 2, graphHeight / 2 - i, graphWidth / 2 + graphWidth / 2, graphHeight / 2 - i);
            g.drawLine(graphWidth / 2 - graphWidth / 2, graphHeight / 2 + i, graphWidth / 2 + graphWidth / 2, graphHeight / 2 + i);
        }

        g2d.setColor(new Color(253, 0, 84));
        //Vẽ nửa trục Ox dương
        g2d.drawLine(graphWidth / 2, graphHeight / 2, graphWidth, graphHeight / 2);
        g2d.drawString("x", graphWidth - 10, graphHeight / 2 - 10); // Vẽ tên trục 
        g2d.drawLine(graphWidth - 5, graphHeight / 2 - 5, graphWidth, graphHeight / 2); //Vẽ mũi tên
        g2d.drawLine(graphWidth - 5, graphHeight / 2 + 5, graphWidth, graphHeight / 2); //Vẽ mũi tên

        //Vẽ nửa trục Oz dương
        g2d.drawLine(graphWidth / 2, 0, graphWidth / 2, graphHeight / 2);
        g2d.drawString("z", graphWidth / 2 + 10, 0 + 10); //Vẽ tên trục
        g2d.drawLine(graphWidth / 2 - 5, 5, graphWidth / 2, 0); //Vẽ mũi tên
        g2d.drawLine(graphWidth / 2 + 5, 5, graphWidth / 2, 0); //Vẽ múi tên

        //Vẽ tâm O
        g2d.drawString("O", graphWidth / 2 - 15, graphHeight / 2 + 15);

        //Vẽ nửa trục Oy dương 
        Point2D a = Rotation.rotateAroundO(-graphHeight / 8 - 11, 0, 45 * Math.PI / 180);
        g2d.drawLine(graphWidth / 2, graphHeight / 2, a.getNewX(), a.getNewY());

        g2d.drawString("y", a.getNewX() - 3, a.getNewY() - 15); //Vẽ tên trục
        g2d.drawLine(a.getNewX() - 1, a.getNewY() - 7, a.getNewX(), a.getNewY()); //Vẽ mũi tên
        g2d.drawLine(a.getNewX() + 11, a.getNewY() - 3, a.getNewX(), a.getNewY()); //Vẽ mũi tên

        //Vẽ nét đứt từ đây ---------------------
        float[] dashingPattern2 = {10f, 4f};
        Stroke dashed = new BasicStroke(1f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER, 1.0f, dashingPattern2, 0.0f);
        g2d.setStroke(dashed);

        g2d.setColor(new Color(146, 154, 171));

        g2d.drawLine(graphWidth / 2, graphHeight / 2, graphWidth / 2, graphHeight); //Vẽ nửa trục Oz âm 
        g2d.drawLine(0, graphHeight / 2, graphWidth / 2, graphHeight / 2); //Vẽ nửa trục Ox âm 

        //Vẽ nửa trục Oz âm
        Point2D b = Rotation.rotateAroundO(graphHeight, 0, 45 * Math.PI / 180);
        g2d.drawLine(graphWidth / 2, graphHeight / 2, b.getNewX(), b.getNewY());
        
        g.setColor(new Color(57, 62, 70));
        if(!list.isEmpty()) {
            list.forEach(shape3D -> {
                shape3D.draw(g);
            });
        }
        else {
            detail.setText(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cudboidDialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        x_cuboid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        y_cuboid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        z_cuboid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        length_cuboid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        width_cuboid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        height_cuboid = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        reset_cuboid = new javax.swing.JButton();
        drawCuboid = new javax.swing.JButton();
        sphereDialog = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        x_sphere = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        y_sphere = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        z_sphere = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        r_sphere = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        reset_sphere = new javax.swing.JButton();
        drawSphere = new javax.swing.JButton();
        CylinderDialog = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        x_cylinder = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        y_cylinder = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        z_cylinder = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        r_cylinder = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        h_cylinder = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        reset_cylinder = new javax.swing.JButton();
        drawCylinder = new javax.swing.JButton();
        ConeDialog = new javax.swing.JDialog();
        jPanel15 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        x_cone = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        y_cone = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        z_cone = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        r_cone = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        h_cone = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        reset_cone = new javax.swing.JButton();
        drawCone = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        openCuboidDialog = new javax.swing.JButton();
        openSphereDialog = new javax.swing.JButton();
        openCylinderDialog = new javax.swing.JButton();
        openConeDialog = new javax.swing.JButton();
        undo = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        jPanel_Graph = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                initGraph(g);
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        detail = new javax.swing.JTextArea();

        cudboidDialog.setTitle("Hình hộp chữ nhật");
        cudboidDialog.setBackground(new java.awt.Color(57, 62, 70));
        cudboidDialog.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        cudboidDialog.setLocation(new java.awt.Point(250, 250));
        cudboidDialog.setResizable(false);
        cudboidDialog.setSize(new java.awt.Dimension(381, 250));
        cudboidDialog.setLocationRelativeTo(null);

        jPanel6.setBackground(new java.awt.Color(57, 62, 70));
        jPanel6.setForeground(new java.awt.Color(247, 247, 247));

        jLabel1.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 247, 247));
        jLabel1.setText("A(x, y, z)");

        jPanel2.setOpaque(false);

        x_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        x_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        x_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        x_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        x_cuboid.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 247, 247));
        jLabel3.setText("x");

        jLabel4.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(247, 247, 247));
        jLabel4.setText("y");

        y_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        y_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        y_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        y_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        y_cuboid.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 247, 247));
        jLabel5.setText("z");

        z_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        z_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        z_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        z_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        z_cuboid.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(x_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(y_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(z_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(x_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(y_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(z_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(247, 247, 247));
        jLabel6.setText("Kích thước:");

        jPanel3.setOpaque(false);

        length_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        length_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        length_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        length_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        length_cuboid.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(247, 247, 247));
        jLabel7.setText("dài:");

        jLabel8.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(247, 247, 247));
        jLabel8.setText("rộng:");

        width_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        width_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        width_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        width_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        width_cuboid.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(247, 247, 247));
        jLabel9.setText("cao:");

        height_cuboid.setBackground(new java.awt.Color(57, 62, 70));
        height_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        height_cuboid.setForeground(new java.awt.Color(247, 247, 247));
        height_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        height_cuboid.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(length_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(width_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(height_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(length_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(width_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(height_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jPanel4.setOpaque(false);

        reset_cuboid.setBackground(new java.awt.Color(247, 247, 247));
        reset_cuboid.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        reset_cuboid.setForeground(new java.awt.Color(57, 62, 70));
        reset_cuboid.setText("Xoá");
        reset_cuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        reset_cuboid.setContentAreaFilled(false);
        reset_cuboid.setOpaque(true);
        reset_cuboid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_cuboidActionPerformed(evt);
            }
        });

        drawCuboid.setBackground(new java.awt.Color(247, 247, 247));
        drawCuboid.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        drawCuboid.setForeground(new java.awt.Color(57, 62, 70));
        drawCuboid.setText("Vẽ");
        drawCuboid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        drawCuboid.setContentAreaFilled(false);
        drawCuboid.setOpaque(true);
        drawCuboid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawCuboidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(drawCuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawCuboid, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(reset_cuboid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cudboidDialogLayout = new javax.swing.GroupLayout(cudboidDialog.getContentPane());
        cudboidDialog.getContentPane().setLayout(cudboidDialogLayout);
        cudboidDialogLayout.setHorizontalGroup(
            cudboidDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cudboidDialogLayout.setVerticalGroup(
            cudboidDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sphereDialog.setTitle("Hình cầu");
        sphereDialog.setBackground(new java.awt.Color(57, 62, 70));
        sphereDialog.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        sphereDialog.setLocation(new java.awt.Point(250, 250));
        sphereDialog.setResizable(false);
        sphereDialog.setSize(new java.awt.Dimension(0, 0));
        cudboidDialog.setLocationRelativeTo(null);

        jPanel8.setBackground(new java.awt.Color(57, 62, 70));
        jPanel8.setForeground(new java.awt.Color(247, 247, 247));

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 247, 247));
        jLabel2.setText("Tâm O(x, y, z)");

        jPanel5.setOpaque(false);

        x_sphere.setBackground(new java.awt.Color(57, 62, 70));
        x_sphere.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        x_sphere.setForeground(new java.awt.Color(247, 247, 247));
        x_sphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        x_sphere.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(247, 247, 247));
        jLabel10.setText("x");

        jLabel11.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(247, 247, 247));
        jLabel11.setText("y");

        y_sphere.setBackground(new java.awt.Color(57, 62, 70));
        y_sphere.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        y_sphere.setForeground(new java.awt.Color(247, 247, 247));
        y_sphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        y_sphere.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(247, 247, 247));
        jLabel12.setText("z");

        z_sphere.setBackground(new java.awt.Color(57, 62, 70));
        z_sphere.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        z_sphere.setForeground(new java.awt.Color(247, 247, 247));
        z_sphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        z_sphere.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(x_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(y_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(z_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(x_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(y_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(z_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(247, 247, 247));
        jLabel13.setText("Kích thước:");

        jPanel9.setOpaque(false);

        r_sphere.setBackground(new java.awt.Color(57, 62, 70));
        r_sphere.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        r_sphere.setForeground(new java.awt.Color(247, 247, 247));
        r_sphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        r_sphere.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(247, 247, 247));
        jLabel14.setText("Bán kính: ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(r_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jPanel10.setOpaque(false);

        reset_sphere.setBackground(new java.awt.Color(247, 247, 247));
        reset_sphere.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        reset_sphere.setForeground(new java.awt.Color(57, 62, 70));
        reset_sphere.setText("Xoá");
        reset_sphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        reset_sphere.setContentAreaFilled(false);
        reset_sphere.setOpaque(true);
        reset_sphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_sphereActionPerformed(evt);
            }
        });

        drawSphere.setBackground(new java.awt.Color(247, 247, 247));
        drawSphere.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        drawSphere.setForeground(new java.awt.Color(57, 62, 70));
        drawSphere.setText("Vẽ");
        drawSphere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        drawSphere.setContentAreaFilled(false);
        drawSphere.setOpaque(true);
        drawSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawSphereActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(drawSphere, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_sphere, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawSphere, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(reset_sphere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel13))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sphereDialogLayout = new javax.swing.GroupLayout(sphereDialog.getContentPane());
        sphereDialog.getContentPane().setLayout(sphereDialogLayout);
        sphereDialogLayout.setHorizontalGroup(
            sphereDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sphereDialogLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sphereDialogLayout.setVerticalGroup(
            sphereDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        CylinderDialog.setTitle("Hình trụ");
        CylinderDialog.setBackground(new java.awt.Color(57, 62, 70));
        CylinderDialog.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        CylinderDialog.setLocation(new java.awt.Point(250, 250));
        CylinderDialog.setResizable(false);
        CylinderDialog.setSize(new java.awt.Dimension(0, 0));
        cudboidDialog.setLocationRelativeTo(null);

        jPanel11.setBackground(new java.awt.Color(57, 62, 70));
        jPanel11.setForeground(new java.awt.Color(247, 247, 247));

        jLabel15.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(247, 247, 247));
        jLabel15.setText("Tâm đáy O(x, y, z)");

        jPanel12.setOpaque(false);

        x_cylinder.setBackground(new java.awt.Color(57, 62, 70));
        x_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        x_cylinder.setForeground(new java.awt.Color(247, 247, 247));
        x_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        x_cylinder.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(247, 247, 247));
        jLabel16.setText("x");

        jLabel17.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(247, 247, 247));
        jLabel17.setText("y");

        y_cylinder.setBackground(new java.awt.Color(57, 62, 70));
        y_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        y_cylinder.setForeground(new java.awt.Color(247, 247, 247));
        y_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        y_cylinder.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(247, 247, 247));
        jLabel18.setText("z");

        z_cylinder.setBackground(new java.awt.Color(57, 62, 70));
        z_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        z_cylinder.setForeground(new java.awt.Color(247, 247, 247));
        z_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        z_cylinder.setOpaque(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(x_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(y_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(z_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(x_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(y_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(z_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(247, 247, 247));
        jLabel19.setText("Kích thước:");

        jPanel13.setOpaque(false);

        r_cylinder.setBackground(new java.awt.Color(57, 62, 70));
        r_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        r_cylinder.setForeground(new java.awt.Color(247, 247, 247));
        r_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        r_cylinder.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(247, 247, 247));
        jLabel20.setText("Bán kính: ");

        jLabel21.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(247, 247, 247));
        jLabel21.setText("Chiều cao:");

        h_cylinder.setBackground(new java.awt.Color(57, 62, 70));
        h_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        h_cylinder.setForeground(new java.awt.Color(247, 247, 247));
        h_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        h_cylinder.setOpaque(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(h_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(r_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jPanel14.setOpaque(false);

        reset_cylinder.setBackground(new java.awt.Color(247, 247, 247));
        reset_cylinder.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        reset_cylinder.setForeground(new java.awt.Color(57, 62, 70));
        reset_cylinder.setText("Xoá");
        reset_cylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        reset_cylinder.setContentAreaFilled(false);
        reset_cylinder.setOpaque(true);
        reset_cylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_cylinderActionPerformed(evt);
            }
        });

        drawCylinder.setBackground(new java.awt.Color(247, 247, 247));
        drawCylinder.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        drawCylinder.setForeground(new java.awt.Color(57, 62, 70));
        drawCylinder.setText("Vẽ");
        drawCylinder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        drawCylinder.setContentAreaFilled(false);
        drawCylinder.setOpaque(true);
        drawCylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawCylinderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(drawCylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_cylinder, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawCylinder, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(reset_cylinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CylinderDialogLayout = new javax.swing.GroupLayout(CylinderDialog.getContentPane());
        CylinderDialog.getContentPane().setLayout(CylinderDialogLayout);
        CylinderDialogLayout.setHorizontalGroup(
            CylinderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        CylinderDialogLayout.setVerticalGroup(
            CylinderDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        ConeDialog.setTitle("Hình nón");
        ConeDialog.setBackground(new java.awt.Color(57, 62, 70));
        ConeDialog.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        ConeDialog.setLocation(new java.awt.Point(250, 250));
        ConeDialog.setResizable(false);
        ConeDialog.setSize(new java.awt.Dimension(0, 0));
        cudboidDialog.setLocationRelativeTo(null);

        jPanel15.setBackground(new java.awt.Color(57, 62, 70));
        jPanel15.setForeground(new java.awt.Color(247, 247, 247));

        jLabel22.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(247, 247, 247));
        jLabel22.setText("Tâm đáy O(x, y, z)");

        jPanel16.setOpaque(false);

        x_cone.setBackground(new java.awt.Color(57, 62, 70));
        x_cone.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        x_cone.setForeground(new java.awt.Color(247, 247, 247));
        x_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        x_cone.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(247, 247, 247));
        jLabel23.setText("x");

        jLabel24.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(247, 247, 247));
        jLabel24.setText("y");

        y_cone.setBackground(new java.awt.Color(57, 62, 70));
        y_cone.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        y_cone.setForeground(new java.awt.Color(247, 247, 247));
        y_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        y_cone.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(247, 247, 247));
        jLabel25.setText("z");

        z_cone.setBackground(new java.awt.Color(57, 62, 70));
        z_cone.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        z_cone.setForeground(new java.awt.Color(247, 247, 247));
        z_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        z_cone.setOpaque(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(x_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(y_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(z_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(x_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(y_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(z_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(247, 247, 247));
        jLabel26.setText("Kích thước:");

        jPanel17.setOpaque(false);

        r_cone.setBackground(new java.awt.Color(57, 62, 70));
        r_cone.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        r_cone.setForeground(new java.awt.Color(247, 247, 247));
        r_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        r_cone.setOpaque(false);

        jLabel27.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(247, 247, 247));
        jLabel27.setText("Bán kính: ");

        jLabel28.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(247, 247, 247));
        jLabel28.setText("Chiều cao:");

        h_cone.setBackground(new java.awt.Color(57, 62, 70));
        h_cone.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        h_cone.setForeground(new java.awt.Color(247, 247, 247));
        h_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        h_cone.setOpaque(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(r_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(r_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(h_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jPanel18.setOpaque(false);

        reset_cone.setBackground(new java.awt.Color(247, 247, 247));
        reset_cone.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        reset_cone.setForeground(new java.awt.Color(57, 62, 70));
        reset_cone.setText("Xoá");
        reset_cone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        reset_cone.setContentAreaFilled(false);
        reset_cone.setOpaque(true);
        reset_cone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_coneActionPerformed(evt);
            }
        });

        drawCone.setBackground(new java.awt.Color(247, 247, 247));
        drawCone.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        drawCone.setForeground(new java.awt.Color(57, 62, 70));
        drawCone.setText("Vẽ");
        drawCone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        drawCone.setContentAreaFilled(false);
        drawCone.setOpaque(true);
        drawCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawConeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(drawCone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reset_cone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawCone, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(reset_cone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ConeDialogLayout = new javax.swing.GroupLayout(ConeDialog.getContentPane());
        ConeDialog.getContentPane().setLayout(ConeDialogLayout);
        ConeDialogLayout.setHorizontalGroup(
            ConeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ConeDialogLayout.setVerticalGroup(
            ConeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vẽ 3D");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(57, 62, 70));
        jPanel7.setFocusTraversalPolicyProvider(true);
        jPanel7.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(426, 80));

        openCuboidDialog.setBackground(new java.awt.Color(146, 154, 171));
        openCuboidDialog.setBorder(null);
        openCuboidDialog.setBorderPainted(false);
        openCuboidDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openCuboidDialog.setFocusPainted(false);
        openCuboidDialog.setFocusable(false);
        openCuboidDialog.setPreferredSize(new java.awt.Dimension(50, 50));
        openCuboidDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCuboidDialogActionPerformed(evt);
            }
        });

        openSphereDialog.setBackground(new java.awt.Color(146, 154, 171));
        openSphereDialog.setBorder(null);
        openSphereDialog.setBorderPainted(false);
        openSphereDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openSphereDialog.setFocusPainted(false);
        openSphereDialog.setFocusable(false);
        openSphereDialog.setPreferredSize(new java.awt.Dimension(50, 50));
        openSphereDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openSphereDialogActionPerformed(evt);
            }
        });

        openCylinderDialog.setBackground(new java.awt.Color(146, 154, 171));
        openCylinderDialog.setBorder(null);
        openCylinderDialog.setBorderPainted(false);
        openCylinderDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openCylinderDialog.setFocusPainted(false);
        openCylinderDialog.setFocusable(false);
        openCylinderDialog.setPreferredSize(new java.awt.Dimension(50, 50));
        openCylinderDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCylinderDialogActionPerformed(evt);
            }
        });

        openConeDialog.setBackground(new java.awt.Color(146, 154, 171));
        openConeDialog.setBorder(null);
        openConeDialog.setBorderPainted(false);
        openConeDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        openConeDialog.setFocusPainted(false);
        openConeDialog.setFocusable(false);
        openConeDialog.setPreferredSize(new java.awt.Dimension(50, 50));
        openConeDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openConeDialogActionPerformed(evt);
            }
        });

        undo.setText("Undo");
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });

        redo.setText("Redo");
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(openCuboidDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openSphereDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openCylinderDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(openConeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(undo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(undo)
                        .addComponent(redo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(openConeDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openCylinderDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openSphereDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openCuboidDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Graph.setBackground(new java.awt.Color(247, 247, 247));
        jPanel_Graph.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jPanel_Graph.setPreferredSize(new java.awt.Dimension(856, 618));

        javax.swing.GroupLayout jPanel_GraphLayout = new javax.swing.GroupLayout(jPanel_Graph);
        jPanel_Graph.setLayout(jPanel_GraphLayout);
        jPanel_GraphLayout.setHorizontalGroup(
            jPanel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_GraphLayout.setVerticalGroup(
            jPanel_GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        detail.setEditable(false);
        detail.setBackground(new java.awt.Color(57, 62, 70));
        detail.setColumns(5);
        detail.setFont(new java.awt.Font("Roboto Mono", 0, 12)); // NOI18N
        detail.setForeground(new java.awt.Color(247, 247, 247));
        detail.setLineWrap(true);
        detail.setRows(5);
        detail.setTabSize(2);
        detail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        jScrollPane2.setViewportView(detail);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addComponent(jPanel_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addComponent(jPanel_Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openCuboidDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCuboidDialogActionPerformed
        // TODO add your handling code here:
        cudboidDialog.pack();
        cudboidDialog.setLocationRelativeTo(null);
        cudboidDialog.setVisible(true);
    }//GEN-LAST:event_openCuboidDialogActionPerformed

    private void drawCuboidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCuboidActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(x_cuboid.getText());
        int y = Integer.parseInt(y_cuboid.getText());
        int z = Integer.parseInt(z_cuboid.getText());

        int width = Integer.parseInt(width_cuboid.getText());
        int length = Integer.parseInt(length_cuboid.getText());
        int height = Integer.parseInt(height_cuboid.getText());

        g.setColor(new Color(57, 62, 70));
        Shape3D cuboid = new Cuboid(x, y, z, length, width, height);
        cuboid.draw(g);
        
        list.add(cuboid);
        reset_cuboid.doClick();
        cudboidDialog.dispose();


    }//GEN-LAST:event_drawCuboidActionPerformed

    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
        // TODO add your handling code here:
        Shape3D a = list.get(list.size() - 1);
        list.remove(list.size() - 1);

        jPanel_Graph.repaint();
        listRedo.add(a);

    }//GEN-LAST:event_undoActionPerformed

    private void drawSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawSphereActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(x_sphere.getText());
        int y = Integer.parseInt(y_sphere.getText());
        int z = Integer.parseInt(z_sphere.getText());

        int r = Integer.parseInt(r_sphere.getText());
        
        g.setColor(new Color(57, 62, 70));
        Sphere sphere = new Sphere(x, y, z, r);
        sphere.draw(g);
        
        list.add(sphere);
        reset_sphere.doClick();
        sphereDialog.dispose();
    }//GEN-LAST:event_drawSphereActionPerformed

    private void openSphereDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSphereDialogActionPerformed
        // TODO add your handling code here:
        sphereDialog.setVisible(true);
        sphereDialog.pack();
        sphereDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_openSphereDialogActionPerformed

    private void drawCylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawCylinderActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(x_cylinder.getText());
        int y = Integer.parseInt(y_cylinder.getText());
        int z = Integer.parseInt(z_cylinder.getText());

        int r = Integer.parseInt(r_cylinder.getText());
        int h = Integer.parseInt(h_cylinder.getText());

        g.setColor(new Color(57, 62, 70));
        Shape3D cylinder = new Cylinder(x, y, z, r, h);
        cylinder.draw(g);
        
        list.add(cylinder);
        reset_cylinder.doClick();
        CylinderDialog.dispose();
    }//GEN-LAST:event_drawCylinderActionPerformed

    private void openCylinderDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCylinderDialogActionPerformed
        // TODO add your handling code here:
        CylinderDialog.pack();
        CylinderDialog.setLocationRelativeTo(null);
        CylinderDialog.setVisible(true);
    }//GEN-LAST:event_openCylinderDialogActionPerformed

    private void drawConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawConeActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(x_cone.getText());
        int y = Integer.parseInt(y_cone.getText());
        int z = Integer.parseInt(z_cone.getText());

        int r = Integer.parseInt(r_cone.getText());
        int h = Integer.parseInt(h_cone.getText());

        g.setColor(new Color(57, 62, 70));
        Shape3D cone = new Cone(new Point3D(x, y, z), r, h);
        cone.draw(g);
        
        list.add(cone);
        reset_cone.doClick();
        ConeDialog.dispose();
    }//GEN-LAST:event_drawConeActionPerformed

    private void openConeDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openConeDialogActionPerformed
        // TODO add your handling code here:
        ConeDialog.pack();
        ConeDialog.setLocationRelativeTo(null);
        ConeDialog.setVisible(true);
    }//GEN-LAST:event_openConeDialogActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:

        Shape3D a = listRedo.get(listRedo.size() - 1);
        list.add(a);
        jPanel_Graph.repaint();
        listRedo.remove(listRedo.size() - 1);

    }//GEN-LAST:event_redoActionPerformed

    private void reset_cuboidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_cuboidActionPerformed
        // TODO add your handling code here:
        x_cuboid.setText(null);
        y_cuboid.setText(null);
        z_cuboid.setText(null);

        height_cuboid.setText(null);
        width_cuboid.setText(null);
        length_cuboid.setText(null);
    }//GEN-LAST:event_reset_cuboidActionPerformed

    private void reset_sphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_sphereActionPerformed
        // TODO add your handling code here:
        x_sphere.setText(null);
        y_sphere.setText(null);
        z_sphere.setText(null);
        
        r_sphere.setText(null);
    }//GEN-LAST:event_reset_sphereActionPerformed

    private void reset_cylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_cylinderActionPerformed
        // TODO add your handling code here:
        x_cylinder.setText(null);
        y_cylinder.setText(null);
        z_cylinder.setText(null);
        
        r_cylinder.setText(null);
        h_cylinder.setText(null);
    }//GEN-LAST:event_reset_cylinderActionPerformed

    private void reset_coneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_coneActionPerformed
        // TODO add your handling code here:
        x_cone.setText(null);
        y_cone.setText(null);
        z_cone.setText(null);
        
        r_cone.setText(null);
        h_cone.setText(null);
    }//GEN-LAST:event_reset_coneActionPerformed

    public void test(Graphics g) {
//        Cylinder cone = new Cylinder(0, 0, 0, 20, 30);
//        cone.draw(g, detail);

//            Cone cone = new Cone(new Point3D(0, 0, 0), 20, 40);
//            cone.draw(g, detail);
//            Sphere sphere = new Sphere(0, 0, 0, 22);
//            sphere.draw(g, detail);
//          Pyramid p = new Pyramid(0, 0, 0, 40, 20, 30);
//          p.draw(g);
//          Cuboid cuboid = new Cuboid(new Point3D(-23, 11, -42), 33, 21, 29);
//          Cuboid cuboid2 = new Cuboid(new Point3D(0,0,0), 30, 20, 30);
//          cuboid2.draw(g, detail);
//            DashedLine dl = new DashedLine(0,0,5, 5);
//            dl.draw(g);
//          Ellipse ellipse = new Ellipse(0, 0, 20, 10);
//          ellipse.draw(g);
//            Point2D a = Quay.rotateAroundO(-1000, 0, 45 * Math.PI/180);
//            a.draw(g);
//            g.drawLine(graphWidth/2, graphHeight/2, a.getNewX(), a.getNewY());
//            System.out.println("run test");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTDH_Nhom8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTDH_Nhom8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTDH_Nhom8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTDH_Nhom8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new KTDH_Nhom8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ConeDialog;
    private javax.swing.JDialog CylinderDialog;
    private javax.swing.JDialog cudboidDialog;
    private javax.swing.JTextArea detail;
    private javax.swing.JButton drawCone;
    private javax.swing.JButton drawCuboid;
    private javax.swing.JButton drawCylinder;
    private javax.swing.JButton drawSphere;
    private javax.swing.JTextField h_cone;
    private javax.swing.JTextField h_cylinder;
    private javax.swing.JTextField height_cuboid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Graph;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField length_cuboid;
    private javax.swing.JButton openConeDialog;
    private javax.swing.JButton openCuboidDialog;
    private javax.swing.JButton openCylinderDialog;
    private javax.swing.JButton openSphereDialog;
    private javax.swing.JTextField r_cone;
    private javax.swing.JTextField r_cylinder;
    private javax.swing.JTextField r_sphere;
    private javax.swing.JButton redo;
    private javax.swing.JButton reset_cone;
    private javax.swing.JButton reset_cuboid;
    private javax.swing.JButton reset_cylinder;
    private javax.swing.JButton reset_sphere;
    private javax.swing.JDialog sphereDialog;
    private javax.swing.JButton undo;
    private javax.swing.JTextField width_cuboid;
    private javax.swing.JTextField x_cone;
    private javax.swing.JTextField x_cuboid;
    private javax.swing.JTextField x_cylinder;
    private javax.swing.JTextField x_sphere;
    private javax.swing.JTextField y_cone;
    private javax.swing.JTextField y_cuboid;
    private javax.swing.JTextField y_cylinder;
    private javax.swing.JTextField y_sphere;
    private javax.swing.JTextField z_cone;
    private javax.swing.JTextField z_cuboid;
    private javax.swing.JTextField z_cylinder;
    private javax.swing.JTextField z_sphere;
    // End of variables declaration//GEN-END:variables
}
